from django.conf.urls import url
from . import views           # This line is new!
urlpatterns = [
    url(r'^$', views.index),     # index.html
    url(r'^signin$', views.signin),     # signin page in login.html
    url(r'^signin/login$', views.login),     # Post signing in user
    url(r'^register$', views.register),     # register new user in login.htm (register.html name did not work.....)
    #url(r'^new_member$', views.new_member),     # Post registering user to dbase    
    url(r'^register/create$', views.create),     # Post registering user to dbase
    url(r'^success/(?P<user_id>\d+)$', views.success, name='success'),     # sends to either views.userdbd or views.admindbd
    url(r'^logoff$', views.logoff),     # This line has changed!    
    #url(r'^start$', views.start),     # This line has changed!    
    
    url(r'^dashboard/user$', views.userdbd, name="user_dashboard"),     # main admin dashboard for members, when logged in...userdash.html
    url(r'^dashboard/admin$', views.admindbd, name="admin_dashboard"),     # main admin dashboard when logged in....admindash.html
    url(r'^users/admin/new$', views.new),#     # admin adds new user to dashboard
    url(r'^users/admin/new/create$', views.createNew),     # posts new user to dbase...
    url(r'^users/(?P<user_id>\d+)/show$', views.show),# show profile of user, selected from dashboards.....
    url(r'^users/(?P<user_id>\d+)/show/post_message$', views.post_message),# show profile of user, selected from dashboards.....
    url(r'^users/(?P<user_id>\d+)/(?P<message_id>\d+)/show/post_comment$', views.post_comment),     # allow admins to edit any, users to edit own profile...

    url(r'^users/(?P<user_id>\d+)/edit$', views.edit),     # allow admins to edit any, users to edit own profile...
    url(r'^users/(?P<user_id>\d+)/edit/update$', views.edit_update),     # allow admins to edit any, users to edit own profile...
    url(r'^users/(?P<user_id>\d+)/edit/pwupdate$', views.password_update),     # allow admins to edit any, users to edit own profile...
    url(r'^users/(?P<user_id>\d+)/edit/description$', views.description_update),     # allow admins to edit any, users to edit own profile...
    url(r'^users/(?P<user_id>\d+)/update$', views.update),     # allow admins to edit any, users to edit own profile...    
    url(r'^users/(?P<user_id>\d+)/destroy$', views.destroy),     # allow admins to edit any, users to edit own profile...
    

]
