# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userd', '0002_auto_20180130_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='muser_id',
            new_name='cuser_id',
        ),
    ]
