# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userd', '0004_remove_comment_cuser_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='cuser',
        ),
    ]
